listen: ":8080"

connections:
  - name: AWX
    type: awx
    role: source
    scheme: http
    host: awx.lab.local
    port: 32000
    username: admin
    password: secret
    insecure: true

  - name: AAP 2.4 RPM
    type: aap
    role: source
    scheme: https
    host: aap24rpm.lab.local
    port: 443
    username: admin
    password: secret
    insecure: false
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      ...
      ...
      ...==
      -----END CERTIFICATE-----

  - name: AAP 2.6
    type: aap
    role: destination
    scheme: https
    host: aap.lab.local
    port: 443
    username: admin
    password: secret
    insecure: true
